### PR TITLE
chore: update marinade sdk to latest

### PR DESCRIPTION
**Pull request by AlexStefan**

### CODE REVIEW

**Comment by MjCage** [comment]
@AlexStefan all of my devnet stake accounts were undelegated. Need to wait for activation to complete this one.

**Review by MjCage — APPROVED** [review]
Looks good :)

**Comment by MjCage** [comment]
@AlexStefan lets go up to 4.0.2 and then we can merge :))

**Comment by AlexStefan** [comment]
@MjCage used this PR to update more deps. Sadly the style of few buttons got broken

**Review by MjCage — APPROVED** [review]
Looks good, txs work.

**Pull request merged**
